Update pr-title-check.yml

diff --git a/.github/workflows/pr-title-check.yml b/.github/workflows/pr-title-check.yml
--- a/.github/workflows/pr-title-check.yml
+++ b/.github/workflows/pr-title-check.yml
@@ -13,14 +13,14 @@ jobs:
     steps:
       - id: validate_title
         run: |
-          [[ "${{ github.event.pull_request.title }}" =~ "${{ env.PR_TITLE_PATTERN }}" ]]
-          valid_title=$?
-          echo $valid_title
-          echo "valid_title=$valid_title" >> $GITHUB_OUTPUT
-          exit $valid_title
+          if ! [[ "${{ github.event.pull_request.title }}" =~ $PR_TITLE_PATTERN ]]; then
+            echo "ERROR: Pull request title does not match required format. E.g. [ONB-314] Add password reset flow"
+            echo "valid_title=false" >> $GITHUB_OUTPUT
+            exit 1
+          fi
       
       - uses: actions/github-script@v6
-        if: ${{ steps.validate_title.outputs.valid_title > 0 }}
+        if: ${{ steps.validate_title.outputs.valid_title == 'false' }}
         with:
           script: |
             github.rest.issues.createComment({
